# Generated by Django 3.1.1 on 2020-09-09 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
