# Generated by Django 3.1.1 on 2020-09-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_transaction_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_posted',
            new_name='date',
        ),
    ]
