# Generated by Django 3.1.1 on 2020-09-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200909_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authorised',
            field=models.BooleanField(default=False),
        ),
    ]
