# Generated by Django 3.1.1 on 2020-09-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_transaction_authorised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(default=market.models.get_bank, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
