# Generated by Django 3.1.1 on 2020-09-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200910_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Default', help_text='Deposit, Withdrawal, Exchange, ect.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.TextField(blank=True, help_text='List of items, details of transaction. Please provide prices where possible.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.BigIntegerField(help_text='Value of transaction in ISK/Bee Bonds'),
        ),
    ]
