# Generated by Django 3.1.1 on 2020-09-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200911_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('pos', 'Recieving Bee Bonds'), ('neg', 'Spending Bee Bonds')], default='neg', max_length=3),
        ),
    ]
