# Generated by Django 3.1.1 on 2020-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_transaction_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('Recieving Bee Bonds', 'Recieving Bee Bonds'), ('Spending Bee Bonds', 'Spending Bee Bonds')], default='Spending Bee Bonds', max_length=25),
        ),
    ]
