# Generated by Django 3.1.1 on 2020-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20200911_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('Recieving', 'Recieving Bee Bonds'), ('Spending', 'Spending Bee Bonds')], default='Spending', max_length=25),
        ),
    ]
